### ISSUE TITLE
bug: Amp_v2

### ISSUE THREAD

**Issue by umbri** [amphp/redis#43]
```
php examples/basic.php
PHP Fatal error:  Uncaught Exception: Invalid file descriptor in /home/vendor/amphp/redis/vendor/amphp/amp/lib/Loop/EvDriver.php:187
Stack trace:
#0 /home/vendor/amphp/redis/vendor/amphp/amp/lib/Loop/EvDriver.php(187): EvLoop->io(Object(Amp\Socket\Socket), 1, Object(Closure), Object(Amp\Internal\Watcher))
#1 /home/vendor/amphp/redis/vendor/amphp/amp/lib/Loop/Driver.php(98): Amp\Loop\EvDriver->activate(Array)
#2 /home/vendor/amphp/redis/vendor/amphp/amp/lib/Loop/Driver.php(71): Amp\Loop\Driver->tick()
#3 /home/vendor/amphp/redis/vendor/amphp/amp/lib/Loop/EvDriver.php(143): Amp\Loop\Driver->run()
#4 /home/vendor/amphp/redis/vendor/amphp/amp/lib/Loop.php(53): Amp\Loop\EvDriver->run()
#5 /home/vendor/amphp/redis/examples/basic.php(11): Amp\Loop::run(Object(Closure))
#6 {main}
  thrown in /home/vendor/amphp/redis/vendor/amphp/amp/lib/Loop/EvDriver.php on line 187
```

```
PHP Fatal error:  Uncaught RuntimeException: UV_EBADF: Bad file descriptor in /home/vendor/amphp/redis/vendor/amphp/amp/lib/Loop/UvDriver.php:49
Stack trace:
#0 [internal function]: Amp\Loop\UvDriver->Amp\Loop\{closure}(Resource id #78, -9, 0, Resource id #77)
#1 /home/vendor/amphp/redis/vendor/amphp/amp/lib/Loop/UvDriver.php(163): uv_run(Resource id #22, 1)
#2 /home/vendor/amphp/redis/vendor/amphp/amp/lib/Loop/Driver.php(127): Amp\Loop\UvDriver->dispatch(true)
#3 /home/vendor/amphp/redis/vendor/amphp/amp/lib/Loop/Driver.php(71): Amp\Loop\Driver->tick()
#4 /home/vendor/amphp/redis/vendor/amphp/amp/lib/Loop.php(53): Amp\Loop\Driver->run()
#5 /home/vendor/amphp/redis/examples/basic.php(11): Amp\Loop::run(Object(Closure))
#6 {main}
  thrown in /home/vendor/amphp/redis/vendor/amphp/amp/lib/Loop/UvDriver.php on line 49
```

```
PHP Notice:  Object of class Amp\Socket\Socket could not be converted to int in /home/vendor/amphp/redis/vendor/amphp/amp/lib/Loop/NativeDriver.php on line 242

Notice: Object of class Amp\Socket\Socket could not be converted to int in /home/vendor/amphp/redis/vendor/amphp/amp/lib/Loop/NativeDriver.php on line 242
PHP Notice:  Object of class Amp\Socket\Socket could not be converted to int in /home/vendor/amphp/redis/vendor/amphp/amp/lib/Loop/NativeDriver.php on line 248

Notice: Object of class Amp\Socket\Socket could not be converted to int in /home/vendor/amphp/redis/vendor/amphp/amp/lib/Loop/NativeDriver.php on line 248
```

**Comment by kelunik** [comment]
It's not updated to the latest changes yet.

**Comment by kelunik** [comment]
Closing, because #44 already fixed that.
